//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("Spectre Systems AB")]
[assembly: AssemblyProduct("Jarvis")]
[assembly: AssemblyVersion("0.8.0")]
[assembly: AssemblyFileVersion("0.8.0")]
[assembly: AssemblyInformationalVersion("0.8.0")]
[assembly: AssemblyCopyright("Copyright (c) 2017 Spectre Systems AB")]

